creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    key_groups:
      - age:
          # Add additional host public keys here as needed and run `sops updatekeys`.
          - age16x7tq5ndgm3hr55gqfh2ujecq4hypyjn3vrmm36vam7y0fu5ffes7qt20s
